import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BreadCrumb from "@/components/BreadCrumb";

export const metadata = {
  title: "HFS-app",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" href="/MSZF.jpeg" sizes="any" />
      </head>
      <body>
        <Header />
        <BreadCrumb />
        {/* <div className="bg-fixed bg-[url(/hand_transparent.png)] bg-auto bg-top bg-no-repeat mx-auto z-0"> */}
        <div className=" mx-auto z-0">
          <main className="relative overflow-hidden">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
